_format_version: "3.0"
_transform: true

services:
  - name: ams-auth-service
    url: http://auth:8000
    routes:
      - name: ams-auth-route
        paths:
          - /auth
    plugins:
      - name: auth-rate-limit
        config:
          limit: 10
          period: 1800

  - name: ams-user-org-service
    url: http://user-org:8000
    routes:
      - name: ams-user-org-route
        paths:
          - /user-org
    plugins:
      - name: context-setter
        config:
          required_permission: "view"

  - name: ams-appointment-service
    url: http://appointment:8000
    routes:
      - name: ams-appointment-route
        paths:
          - /appointment
    plugins:
      - name: context-setter
        config:
          required_permission: "book"
