services:
  ams-gateway:
    build: .
    image: ams-gateway:latest
    container_name: ams-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/config/kong.yaml"
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PLUGINS: "auth-rate-limit,context-setter"
    networks:
      - ams-network
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

networks:
  ams-network:
    name: ams-network
    driver: bridge
